### ISSUE TITLE
Provide an icon

### ISSUE THREAD

**Issue by delapuente** [delapuente/wp-offline-content#10]

**Comment by marco-c** [comment]
@digitarald

**Comment by digitarald** [comment]
Before I block shipping this just because I didn't have time to make a proper pull request, here the assets:

![offline icon 01](https://cloud.githubusercontent.com/assets/8599/13517460/9daa79e8-e178-11e5-8afb-a0b4da496d54.png)
![offline icon 01 2x](https://cloud.githubusercontent.com/assets/8599/13517461/9dab9404-e178-11e5-87b4-0cbe9e782532.png)
![offline header-772x250](https://cloud.githubusercontent.com/assets/8599/13517463/a13bbf54-e178-11e5-8485-056712f983e1.png)
![offline header-1544x500](https://cloud.githubusercontent.com/assets/8599/13517464/a13dd38e-e178-11e5-946f-c3b02f8d7b63.png)

**Comment by digitarald** [comment]
Icon reference: https://thenounproject.com/search/?q=Disconnect&i=60024

**Comment by delapuente** [comment]
Done!
